- name: Set up PVC directory
  hosts: all
  become: true
  tasks:
    - name: Create master PVC directory
      file:
        path: /home/ubuntu/pv-master
        state: directory
        owner: 1000
        group: 1000 
        mode: '0770'
        recurse: true
      # when: inventory_hostname in groups['k3s_server']

    - name: Create data PVC directory
      file:
        path: /home/ubuntu/pv-data
        state: directory
        owner: 1000
        group: 1000
        mode: '0770'
        recurse: true
      # when: inventory_hostname in groups['k3s_agent']

    - name: Create virtual environment
      shell: python3 -m venv .venv

    - name: Activate virtual environment
      shell: source .venv/bin/activate
      args:
        executable: /bin/bash

    - name:
      shell: | 
        kubectl get po -A

    - name: Activate bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
